# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BitBucketList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FlexLayout'
  pod 'PinLayout'
  pod 'AlamofireImage'
  pod 'Moya', '~> 14.0'
  pod 'lottie-ios'
 
  # Pods for BitBucketList

  

end
